### ISSUE TITLE
Using Auto Color in Bitwig 3.1.2 (Doesn't Auto-Color)

### ISSUE THREAD

**Issue by Taylorrowley** [git-moss/Utils4Bitwig#1]
Hi!

I've been watching your series on programming Bitwig controllers, and I heard you mention you had created this, and I wanted to try it out cause I am always constantly recoloring my tracks.  I can't seem to get it to work, i drag in tracks from the browser on the side but the tracks do not auto color. I've attached an image of the strings I've entered, it's possible I'm just doing it wrong.

![Annotation 2020-01-18 222717](https://user-images.githubusercontent.com/60053867/72674172-b8723880-3a41-11ea-819d-cee02ddc8651.png)

**Comment by git-moss** [comment]
Remove the quotation then it should work fine.

**Comment by Taylorrowley** [comment]
Yep that works! Thanks, show how much I know lol!
